import type { Metadata } from "next";
import "./globals.css";
import SideNav from "./_components/Sidenav";
import { ThemeProvider } from "./providers";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
  // Optional: You can add 'variable: "--font-roboto"' if you plan to use tailwind config for font-sans/body replacement
});

export const metadata: Metadata = {
  title: "Darkah Task App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.className} antialiased transition-colors duration-300 bg-app-bg text-app-gray`}
      >
        <ThemeProvider
          attribute="data-theme"
          defaultTheme="system"
          enableSystem
        >
          <div>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
